<?php
/**
 * Tracker class for WP Demo Content Generator.
 *
 * Stores and retrieves the IDs of all content generated by this plugin
 * inside a single wp_options row. Acts as a redundant safety layer
 * alongside the `_wpdcg_generated` post meta flag.
 *
 * All methods are static — no instantiation required.
 *
 * @package WP_Demo_Content_Generator
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class WPDCG_Tracker
 */
class WPDCG_Tracker {

	/**
	 * The wp_options key used to persist generated post IDs.
	 *
	 * @var string
	 */
	const OPTION_KEY = 'wpdcg_generated_ids';

	/**
	 * Returns all tracked post IDs.
	 *
	 * @return int[]
	 */
	public static function get_all_ids() {
		$ids = get_option( self::OPTION_KEY, array() );
		return is_array( $ids ) ? array_values( array_map( 'absint', $ids ) ) : array();
	}

	/**
	 * Merges new IDs into the tracked list.
	 *
	 * @param int[] $ids Post IDs to add.
	 */
	public static function add_ids( array $ids ) {
		$existing = self::get_all_ids();
		$merged   = array_values( array_unique( array_merge( $existing, array_map( 'absint', $ids ) ) ) );
		update_option( self::OPTION_KEY, $merged, false );
	}

	/**
	 * Removes specific IDs from the tracked list.
	 *
	 * @param int[] $ids Post IDs to remove.
	 */
	public static function remove_ids( array $ids ) {
		$existing = self::get_all_ids();
		$remove   = array_map( 'absint', $ids );
		$updated  = array_values( array_diff( $existing, $remove ) );
		update_option( self::OPTION_KEY, $updated, false );
	}

	/**
	 * Wipes the entire tracked list from the database.
	 */
	public static function clear() {
		delete_option( self::OPTION_KEY );
	}

	/**
	 * Returns the total number of tracked items.
	 *
	 * @return int
	 */
	public static function count() {
		return count( self::get_all_ids() );
	}
}

