<?php
/**
 * Cleaner class for WP Demo Content Generator.
 *
 * Safely deletes ONLY the content generated by this plugin.
 * Deletion is scoped to posts carrying the `_wpdcg_generated` post meta flag —
 * real site content is never touched.
 *
 * @package WP_Demo_Content_Generator
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class WPDCG_Cleaner
 */
class WPDCG_Cleaner {

	/**
	 * Deletes all demo content generated by this plugin.
	 *
	 * Queries across all post types and statuses using the meta flag as the
	 * sole selector, then force-deletes (bypasses Trash) each matched post.
	 * The tracker option is cleared afterwards regardless of individual errors.
	 *
	 * @return array {
	 *     @type int      $deleted Number of posts successfully deleted.
	 *     @type string[] $errors  Any per-post error messages.
	 * }
	 */
	public function delete_all() {
		$query = new WP_Query(
			array(
				'post_type'      => 'any',
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'fields'         => 'ids',
				'no_found_rows'  => true,
				'meta_query'     => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
					array(
						'key'   => WPDCG_Generator::META_KEY,
						'value' => '1',
					),
				),
			)
		);

		$deleted = 0;
		$errors  = array();

		foreach ( $query->posts as $post_id ) {
			$result = wp_delete_post( absint( $post_id ), true );

			if ( $result instanceof WP_Post ) {
				$deleted++;
			} else {
				$errors[] = sprintf(
					/* translators: %d: post ID */
					__( 'Could not delete post ID %d.', 'wp-demo-content-generator' ),
					absint( $post_id )
				);
			}
		}

		// Always clear the tracker — the meta flag is the source of truth.
		WPDCG_Tracker::clear();

		return array(
			'deleted' => $deleted,
			'errors'  => $errors,
		);
	}
}

